/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_shizy_android_demo_uninstall_UnInstallManager */

#ifndef _Included_com_shizy_android_demo_uninstall_UnInstallManager
#define _Included_com_shizy_android_demo_uninstall_UnInstallManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_shizy_android_demo_uninstall_UnInstallManager
 * Method:    listen
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_shizy_android_demo_uninstall_UnInstallManager_listen
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
